app/blueprints/search/models.py
from app.helpers import Pagination
import rawes

class BookmarksQuery(object):

    def __init__(self, q=None, ):
        self.es = rawes.Elastic('localhost:9200')

app/__init__.py
import os
import logging
from flask import Flask
from app.extensions.assets import configure_assets

DEFAULT_BLUEPRINTS = [
    ('search', ''),
]


def create_app(config=None, blueprints=None):
    """
    Create and initialise the application.
    """
    app = Flask(__name__)
    app.config.from_pyfile('%s/config/default.py' % app.root_path)

    if config:
        app.config.from_pyfile(config)
    elif os.getenv('FLASK_CONFIG'):
        app.config.from_envvar('FLASK_CONFIG')

    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    #configure_logging(app)
    configure_context_processors(app)

    configure_blueprints(app, blueprints)

    # Configure assets last so that blueprints can have a chance to import and
    # add their static files to the asset bundles.
    configure_assets(app)
    #configure_extensions(app)

    return app


def configure_blueprints(app, blueprints):
    """
    Register blueprints.
    """
    for blueprint in blueprints:
        # Import blueprint from view module
        module = __import__('app.blueprints.%s.views' % blueprint[0], globals(), locals(), '*')
        app.register_blueprint(module.blueprint, url_prefix=blueprint[1])


def configure_context_processors(app):

    @app.context_processor
    def debug(debug=app.debug):
        """
        Notify templates that they're in debug mode
        """
        return dict(debug=debug)


def configure_logging(app):

    if app.debug:
        logging.getLogger().setLevel(logging.DEBUG)
    else:
        log_format = logging.Formatter('''
---
Message type:       %(levelname)s
Location:           %(pathname)s:%(lineno)d
Module:             %(module)s
Function:           %(funcName)s
Time:               %(asctime)s

%(message)s

''')

        # Send errors via email
        mail_handler = logging.handlers.SMTPHandler('127.0.0.1', app.config.get('DEFAULT_MAIL_SENDER'), app.config.get('ERROR_EMAIL'), 'Error')
        mail_handler.setLevel(logging.ERROR)
        mail_handler.setFormatter(log_format)

        # Also continue to log errors to stderr
        stream_handler = logging.StreamHandler()
        stream_handler.setFormatter(log_format)

        app.logger.addHandler(stream_handler)
        app.logger.addHandler(mail_handler)

app/blueprints/search/__init__.py
from flask import Blueprint

blueprint = Blueprint('search', __name__, template_folder='templates')

app/blueprints/search/views.py
from pprint import pprint
from flask import request, render_template
import rawes
from app.helpers import Pagination, BellCurvePagination
from . import blueprint


@blueprint.route('/')
def results():

    page = int(request.args.get('page', 1))
    qstr = request.args.get('q', '')
    size = 15

    es = rawes.Elastic('localhost:9200')

    if qstr == '':
        query = {
            'match_all': {}
        }
        sort = {
            'last_updated': 'desc'
        }
    else:
        query = {
            'term': {
                '_all': qstr
            }
        }
        sort = {
            '_score': 'desc'
        }

    #print qstr
    #print query

    results = es.get('bookmarks/bookmark/_search', data={
        'version': True,
        'query': query,
        'fields': ['title', 'archive_url', 'last_updated'],
        'size': size,
        'from': (page * size) - size,
        'sort': sort,
    })

    #print results

    pagination = Pagination(page, size, results['hits']['total'], results['hits']['hits'])

    bcpagination = BellCurvePagination(page, size, results['hits']['total'], results['hits']['hits'])

    #print bcpagination.pagination

    #pprint(pagination.pages)

    return render_template('srp.jinja', pagination=bcpagination, qstr=qstr)

fabfile/__init__.py
from fabric.decorators import task

import virtualenv
import app


@task
def build():
    """
    Execute build tasks.
    """
    virtualenv.build()


@task
def run():
    """
    Run app in debug mode (for development).
    """
    app.run()


@task
def freeze():
    """Build app as static site"""
    app.freeze()


@task
def serve_frozen():
    """Build and serve static site up on development server"""
    app.freeze()
    app.serve_frozen()

fabfile/app.py
from fabfile.utils import do
from fabfile.virtualenv import venv_path


def run():
    """Start app in debug mode (for development)."""
    do('export FLASK_CONFIG=config/dev.py && %s/bin/python manage.py runserver' % venv_path)


def freeze():
    """Build app as static site"""
    do('export FLASK_CONFIG=config/dev.py && %s/bin/python manage.py freeze' % venv_path)


def serve_frozen():
    """Serve static site up on development server"""
    do('export FLASK_CONFIG=config/dev.py && %s/bin/python manage.py serve_frozen' % venv_path)

app/blueprints/search/templates/_includes/search_macros.jinja
{% macro search_result(item) %}
    <li>
        <h3><a href="{{ item.link }}" title="{{ item.title|e }}">{{ item.htmlTitle|replace(" | Unum", "") }}</a></h3>
        <p class="url">from <a href="{{ item.link }}" title="{{ item.title|e }}">{{ item.htmlFormattedUrl }}</a></p>
        <p>{{ item.htmlSnippet }}</p>
    </li>
{% endmacro %}

{% macro search_results(results) %}
<ol>
{% for item in results: %}
    {{ search_result(item) }}
{% endfor %}
</ol>
{% endmacro %}

{% macro pagination_ui(num_pages, page, terms) %}
{#
markup based on Mike West's excellent suggestion:
https://mikewest.org/2010/02/an-accessible-pagination-pattern
#}
<p id="paginglabel" class="audible">Pagination</p>
<ul role="navigation" aria-labelledby="paginglabel">
{#{ [num_pages + 1, 8]|sort|first}#}
{% for i in range(1, num_pages + 1) %}
    <li>{{ pagination_item(i, page, terms) }}</li>
{% endfor %}
</ul>
{% endmacro %}

{% macro bcpagination_ui(pagination, current_page, terms) %}
    <div class="pagination">
        <p id="paginglabel" class="audible">Pagination</p>
        <ul role="navigation" aria-labelledby="paginglabel">
        {% for  page in pagination %}
            <li{% if page == current_page %} class="active"{% elif page == '...' %} class="disabled"{% endif %}>{{ pagination_item(page, current_page, terms) }}</li>
        {% endfor %}
        </ul>
    </div>
{% endmacro %}

{% macro pagination_item(i, current, terms) -%}
    {% if i == current %}
        {% call pagination_link(i, terms) %}
            <span class="audible">You&rsquo;re currently reading Search Results Page </span>{{ i }}
        {% endcall %}
    {% elif i == current - 1 %}
        {% call pagination_link(i, terms, rel="prev") %}
            <span class="prev">Previous<span class="audible">: Search Results Page </span></span>{{ i }}
        {% endcall %}
    {% elif i == current + 1 %}
        {% call pagination_link(i, terms, rel="next") %}
            <span class="next">Next<span class="audible">: Search Results Page </span></span>{{ i }}
        {% endcall %}
    {% elif i == '...' %}
        <a>{{ i }}</a>
    {% else %}
        {% call pagination_link(i, terms) %}
            <span class="audible">Search Results Page</span> {{ i }}
        {% endcall %}
    {% endif %}
{%- endmacro %}

{% macro pagination_link(i, terms, rel="") -%}
<a href="{{ url_for('search.results', q=terms, page=i) }}"{% if rel %} rel="{{ rel }}"{% endif %}>{{ caller() }}</a>
{%- endmacro %}

app/blueprints/search/templates/srp.jinja
{% extends 'base.jinja' %}

{% block body %}
    {% from '_includes/search_macros.jinja' import bcpagination_ui %}
    <p>There are {{ pagination.total_count }} results in total.</p>
    <ul>
    {% for result in pagination.items %}
        <li><a href="{{ result['fields']['archive_url'] }}">{{ result['fields']['title'] }}</a></li>
    {% endfor %}
    </ul>
    {#{ pagination_ui(pagination.pages, pagination.page, qstr) }#}
    {{ bcpagination_ui(pagination.pagination, pagination.page, qstr) }}

{% endblock body %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        {% assets 'css_main' -%}
        <link rel="stylesheet{% if ASSET_URL.endswith('.less') %}/less{% endif %}" href="{{ ASSET_URL }}" media="screen" />
        {% endassets %}
    </head>

    <body>

        {% block body %}
        {% endblock body %}

    </body>
</html>